import json
import requests
import threading
import time
import json
import pika
from flask import Flask, Response


BOARDGAME_SERVER = "http://localhost:5000"
MASON = "application/vnd.mason+json"

RABBITMQ_BROKER_URL = "amqp://guest:guest@localhost:5672/%2F?connection_attempts=3&heartbeat=3600"

app = Flask(__name__)

workers = []


"""
Overall system schema:

- One worker and exchange per game instance (Could perhaps be changed to multiple game instances per worker)
- Worker fetches game data from the main API every X seconds
- One queue per spectator
- Exchange name is the game uuid
- Queue name is randomly generated by the spectating client

"""


class SpectatorWorker():

    def __init__(self, game_uuid: str):
        self.game_uuid = game_uuid
        self.game_url = BOARDGAME_SERVER + "/api/games/" + game_uuid
        self.game_json = None
        self.connection = None
        self.channel = None

        resp = requests.get(self.game_url)

        if resp.status_code == 200:
            self.game_found = True
        else:
            self.game_found = False

    def __del__(self):
        self.log("Worker shut down successfully")

    def log(self, message):
        print("Worker " + self.game_uuid[0:5] + ": " + message, flush=True)

    def on_open(self, connection):
        self.channel = connection.channel()
        self.channel.exchange_declare(
            exchange=self.game_uuid,
            exchange_type="fanout"
        )

    def close(self):
        self.log("Shutting down")
        self.connection.close()

    def run(self):
        self.connection = pika.BlockingConnection(
            pika.URLParameters(RABBITMQ_BROKER_URL))
        self.on_open(self.connection)
        while self.connection.is_open:

            resp = requests.get(self.game_url)

            if resp.status_code == 200:
                # If the game state has not changed there is no need to send it
                if resp.json() != self.game_json or self.game_json is None:
                    self.game_json = resp.json()
                    self.channel.basic_publish(
                        exchange=self.game_uuid,
                        routing_key="",
                        body=json.dumps(self.game_json)
                    )
                if self.game_json["result"] != -1:
                    # If the game has finished there probably won't be any updates
                    # so we can stop the worker
                    self.close()
                else:
                    time.sleep(0.5)
            else:
                self.log("ERROR " + resp.status_code +
                         ": Could not get game information")
                self.close()


@app.route("/spectate/<string:game>")
def spectate_game(game):
    global workers

    worker = None

    for w in workers:
        if w.game_uuid == game:
            worker = w
            break

    if worker is None:
        print("Worker not found for " + game + ". Creating a new worker")
        worker = SpectatorWorker(game)

    if worker.game_found:
        thread = threading.Thread(target=worker.run)
        thread.start()
        workers.append(worker)

        resp = {}
        resp["@controls"] = {}
        resp["exchange"] = worker.game_uuid
        resp["@controls"]["amqp-url"] = RABBITMQ_BROKER_URL

        return Response(response=json.dumps(resp), status=200, mimetype=MASON)
    else:
        del worker
        resp = {}
        resp["status"] = "Game was not found"
        resp["@controls"] = {}

        return Response(response=json.dumps(resp), status=404, mimetype=MASON)


if __name__ == "__main__":
    app.run(port=5001)
